clgg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('info.urls')),
    path('info/',include('info.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    
    # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

info/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import timedelta, date
from django.db.models.signals import post_save,post_delete
# Create your models here.
#



sex_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)


class User(AbstractUser):
    @property
    def is_student(self):
        if hasattr(self,'student'):
            return True
        return False

    @property
    def is_teacher(self):
        if hasattr(self,'teacher'):
            return True
        return False



class Dept(models.Model):
    id = models.CharField(primary_key=True,max_length=20)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.id
    

class Class(models.Model):
    id = models.CharField(primary_key=True,max_length=20)
    dept = models.ForeignKey(Dept,on_delete=models.CASCADE)
    section = models.CharField(max_length=20)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'Classes'

    def __str__(self):
        d = Dept.objects.get(id=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)


class Course(models.Model):
    dept = models.ForeignKey(Dept,on_delete=models.CASCADE)
    id = models.CharField(primary_key=True,max_length=20)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length = 50)

    def __str__(self):
        return self.shortname
#    
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null = True)
    dept = models.ForeignKey(Dept,on_delete = models.CASCADE,default = 'CSE')
    class_id = models.ForeignKey(Class,on_delete = models.CASCADE)
    USN = models.CharField(primary_key=True,max_length = 50)
    name = models.CharField(max_length=50)
    sex = models.CharField(max_length=10,choices = sex_choice,default='Male')
    DOB = models.DateField(default='1999-01-01')
    
    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    sex = models.CharField(max_length=10,choices = sex_choice,default='Female')
    id = models.CharField(primary_key=True,max_length=50)
    DOB = models.DateField(default='1990-01-01')
    dept = models.ForeignKey(Dept,on_delete = models.CASCADE,default='CSE')

    def __str__(self):
        return self.name

class Assign(models.Model):
    class_id = models.ForeignKey(Class,on_delete = models.CASCADE)
    course = models.ForeignKey(Course,on_delete = models.CASCADE)
    teacher = models.ForeignKey(Teacher,on_delete = models.CASCADE)

    class Meta:
        unique_together = (('course','class_id','teacher'),)

    def __str__(self):
        cl = Class.objects.get(id = self.class_id_id)
        cr = Course.objects.get(id = self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name,cr.shortname,cl)
    

examnames = {
    1:'Internal Exam 1',
    2:'Internal Exam 2',
    3:'Internal Exam 3',
    4:'External Exam',
}

class Marks(models.Model):
    ass = models.ForeignKey(Assign,on_delete = models.CASCADE)
    examname = models.CharField(max_length=20)
    status = models.CharField(max_length=10,default='0')
    

def create_marks(sender,instance, **kwargs):
    if kwargs['created']:
        for i in range(1,5):
            a = Marks(examname = examnames[i],status='0',ass=instance)
            a.save()

class MarksConfirm(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    marks = models.ForeignKey(Marks,on_delete=models.CASCADE)
    examname = models.CharField(max_length = 20)
    #att = models.BooleanField(default='True')
    #status = models.CharField(max_length=20,default='not marked')
    marksnumber = models.CharField(max_length=10,default='0')

class GetMarks(models.Model):
    student = models.ForeignKey(Student,on_delete = models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student','course'),)

    @property
    def IE1(self):
        stud = Student.objects.get(USN = self.student.USN)
        cr = Course.objects.get(shortname = self.course)
        markss = MarksConfirm.objects.filter(student=stud,course=cr,examname = 'Internal Exam 1')
        if(len(markss)!=0):
            return markss[0].marksnumber
        return "Not Marked"
    
    @property
    def IE2(self):
        stud = Student.objects.get(USN = self.student.USN)
        cr = Course.objects.get(shortname = self.course)
        markss = MarksConfirm.objects.filter(student=stud,course=cr,examname = 'Internal Exam 2')
        if(len(markss)!=0):
            return markss[0].marksnumber
        return "Not Marked"

    @property
    def IE3(self):
        stud = Student.objects.get(USN = self.student.USN)
        cr = Course.objects.get(shortname = self.course)
        markss = MarksConfirm.objects.filter(student=stud,course=cr,examname = 'Internal Exam 3')
        if(len(markss)!=0):
            return markss[0].marksnumber
        return "Not Marked"

    @property
    def EE(self):
        stud = Student.objects.get(USN = self.student.USN)
        cr = Course.objects.get(shortname = self.course)
        markss = MarksConfirm.objects.filter(student=stud,course=cr,examname = 'External Exam')
        if(len(markss)!=0):
            return markss[0].marksnumber
        return "Not Marked"

post_save.connect(create_marks,sender = Assign)
    #Attendance from here on

time_slots = (
    ('9:30-10:30','9:30-10:30'),
    ('11:00-12:00','11:00-12:00'),
    ('1:00-2:00','1:00-2:00'),
    ('2:30-3:30','2:30-3:30'),
)

days_of_week = (
    ('Monday','Monday'),
    ('Tuesday','Tuesday'),
    ('Wednesday','Wednesday'),
    ('Thursday','Thursday'),
    ('Friday','Friday'),
    ('Saturday','Saturday')
)

class AssignTime(models.Model):
    assign = models.ForeignKey(Assign,on_delete = models.CASCADE)
    period = models.CharField(max_length=20,choices = time_slots)
    day = models.CharField(max_length = 10,choices = days_of_week)

days = {
    'Monday':1,
    'Tuesday':2,
    'Wednesday':3,
    'Thursday':4,
    'Friday':5,
    'Saturday':6
}

def daterange(start_date,end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)

def create_attendance(sender,instance,**kwargs):
    if kwargs['created']:
        start_date = date(2020, 9, 1)
        end_date = date(2021, 2, 1)
        for single_date in daterange(start_date,end_date):
            if single_date.isoweekday() == days[instance.day]:
                a = AttendanceClass(date = single_date.strftime("%Y-%m-%d"),assign = instance.assign)
                a.save()
                
class AttendanceClass(models.Model):
    assign = models.ForeignKey(Assign,on_delete = models.CASCADE)
    date = models.DateField()
    status = models.IntegerField(default=0)

post_save.connect(create_attendance,sender = AssignTime)

class Attendance(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete = models.CASCADE)
    status = models.BooleanField(default = True)
    attendanceclass = models.ForeignKey(AttendanceClass,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return self.student+" "+self.course+" "+self.date+" "+self.status

class AttendanceTotal(models.Model):
    student = models.ForeignKey(Student,on_delete = models.CASCADE)
    course = models.ForeignKey(Course,on_delete = models.CASCADE)

    @property
    def total_classes(self):
        stud = Student.objects.get(USN = self.student.USN)
        cr = Course.objects.get(id = self.course.id)
        total_class = Attendance.objects.filter(student=stud,course=cr).count()
        return total_class
    
    @property
    def classes_attended(self):
        stud = Student.objects.get(USN = self.student.USN)
        cr = Course.objects.get(id = self.course.id)
        class_attended = Attendance.objects.filter(student=stud,course=cr,status=True).count()
        return class_attended

    @property
    def attendance_percentage(self):
        if (self.total_classes == 0):
            return 0
        return (self.classes_attended/self.total_classes)*100

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Document| {% block title %}
    {% endblock title %}</title>
  </head>
  <body>
    {% block content %}{% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/base_student.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Student| {% block title %}
    {% endblock title %}</title>
  </head>
  <body>
  <style>
  #loggingout{
    color:grey;
    margin-top:20px;
    margin-right:30px;
  }

  /* The side navigation menu */
.sidebar {
  margin: 0;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

/* Sidebar links */
.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}

/* Active/current link */
.sidebar a.active {
  background-color: #4CAF50;
  color: white;
}

/* Links on mouse-over */
.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

/* Page content. The value of the margin-left property should match the value of the sidebar's width property */
div.content {
  margin-left: 200px;
  padding: 1px 16px;
  height: 1000px;
}

/* On screens that are less than 700px wide, make the sidebar into a topbar */
@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: auto;
    position: relative;
  }
  .sidebar a {float: left;}
  div.content {margin-left: 0;}
}

/* On screens that are less than 400px, display the bar vertically, instead of horizontally */
@media screen and (max-width: 400px) {
  .sidebar a {
    text-align: center;
    float: none;
  }
}
  </style>

{% load static %}
    
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#"><b><p style="font-size:25px;position:relative;top:8px;">{{ request.user.student.name }}</p></b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--<li class="nav-item active ml-4">
        <a class="nav-link" href="#">{{request.user.student.USN}} <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item active ml-4">
        <a class="nav-link" href="#">{{request.user.student.class_id}} <span class="sr-only">(current)</span></a>
      </li>
      -->
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0 mx-5">
      
      <a href="{% url 'logoutuser' %}"  id="loggingout"><b>LOGOUT</b></a>
    </form>
  </div>
</nav>

<div class="sidebar">
  <a class="active" href="#home">Home</a>
  <a href="#news">News</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
</div>

    {% block content %}{% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/base_teacher.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Teacher | {% block title %}
    {% endblock title %}</title>
  </head>
  <body>

        <style>
        #loggingout{
          color:grey;
          margin-top:20px;
          margin-right:30px;
        }
        
        </style>


    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#"><b><p style="font-size:25px;position:relative;top:8px;">{{ request.user.teacher.name }}</p></b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--<li class="nav-item active ml-4">
        <a class="nav-link" href="#">{{request.user.student.USN}} <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item active ml-4">
        <a class="nav-link" href="#">{{request.user.student.class_id}} <span class="sr-only">(current)</span></a>
      </li>
      -->
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0 mx-5">
      
      <a href="{% url 'logoutuser' %}"  id="loggingout"><b>LOGOUT</b></a>
    </form>
  </div>
</nav>

    {% block content %}{% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block title %}login
{% endblock title %}
{% block content %}
<style>
body{
    background: #6A555B;
}
</style>
<div class="container">
        <div class="card card-login mx-auto mt-5">
        <div class="card-header">Login</div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button  class="btn btn-success" type="submit">Login</button>
            </form>
</div>
{% endblock content %}

templates/s_viewattendance.html
{% extends 'base_student.html' %}
{% block title %}View Attendance{% endblock title %}
{% block content %}
<div class="container">
<div class="card mt-4 ml-4">
<div class="card-body">
<div class="table-responsive">
<table class="table table-bordered table-hover">
<thead>
<tr>
<th>Code</th>
<th>Course</th>
<th>Total Classes</th>
<th>Classes Attended</th>
<th>Attendance</th>
</tr></thead>
<tbody>
{% for i in att_total %}
<tr>
<td>{{ i.course }}</td>
<td>{{ i.course.name }}</td>
<td>{{i.total_classes}}</td>
<td>{{i.classes_attended}}</td>
{% if i.attendance_percentage >= 75 %}
<td class="bg-success">{{i.attendance_percentage}}%</td>
{% elif i.total_classes == 0 %}
<td class="bg-success">{{i.attendance_percentage}}%</td>
{% else %}
<td class="bg-danger">{{i.attendance_percentage}}%</td>
{% endif %}
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>
{% endblock content %}

templates/student.html
{% extends 'base_student.html' %}
{% block title %}Home{% endblock title %}
{% block content %}

{% load static %}
<style>
.card{
    float:left;
    margin-left:20px;
    margin-top:100px;
}
img{
    width:40px;
    height:180px;
}
.sidebar{
    display:none;
}
</style>
<div class="container-fluid">
<div class="card" style="width: 18rem;margin-left:100px;">
  <img src='{% static "images/attendance.jpg"%}' class="card-img-top" alt="...">
  <div class="card-body" href="#">
    <h5 class="card-title">View Attendance</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="{% url 's_viewattendance' %}" class="btn btn-primary">View Attendance</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src='{% static "images/marks.jpg"%}' class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">View marks</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="{% url 's_viewmarks' %}" class="btn btn-primary">View Marks</a>
  </div>
</div>
</div>

{% endblock content %}

templates/t_attendance.html
{% extends 'base_teacher.html' %}
{% block title %}Attendance{% endblock title %}
{% block content %}
<div class="container">
<div class="text-black" style="font-size:40px;"><h1>List Of Classes</h1></div>
<div class="card  mt-2">
<div class="card-body">
<div class="table-responsive">
<table class="table table-hover table-bordered table-dark">
  <thead>
    <tr>
      
      <th scope="col">Class</th>
      <th scope="col">Course</th>
      <th scope="col">Code</th>
      
      <th scope="col"></th>
      
    </tr>
  </thead>
  <tbody>
{% for i in ass %}
<tr>

<td>{{ i.class_id }}</td>
<td>{{ i.course }}</td>
<td>{{ i.course_id}} </td>
<td><a href="{% url 't_attendanceclasses' i.id  %}" style="color:white;"><button type="button" class="btn btn-light">Enter Attendance</button></a>&nbsp;&nbsp;
<a href="#"><button type="button" class="btn btn-light">Extra Class</button></a>&nbsp;&nbsp;
<a href="#"><button type="button" class="btn btn-light">View Students</button></a>
</td>


</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>
{% endblock content %}

templates/t_attendanceclasses.html
{% extends 'base_teacher.html' %}
{% block title %}Select Date{% endblock title %}
{% block content %}
<div class="container">
<div class="card">
<div class="card-body">
<div class="table-responsive">
<table class="table table-hover table-bordered table-dark">
<thead>
<tr>
<td>Date</td>
<td>Status</td>
<td></td>
</tr>
</thead>
<tbody>
{% for i in att_list %}
<tr>
<td>{{i.date}} </td>
<td class="bg-danger" width="280px">Not Marked</td>
<td>
{% if i.status == 0 %}
<a href="{% url 't_enterattendance' i.id %}" class="btn btn-light" role="button">Enter Attendance</a>
<a href="#" class="btn btn-light" role="button">Cancel Class</a>
{% else %}
<a href="#">Edit Attendance</a>
{% endif %}


</td>

</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>
{% endblock content %}

templates/t_enterattendance.html
{% extends 'base_teacher.html' %}
{% block title %}Enter Attendance{% endblock title %}
{% block content %}
<div class="container">
<div class="card">
<div class="card-body">
<div class="table-responsive">
<form action="{% url 'submitattendance' ac.id %}" method="post">
{% csrf_token %}
<table class = "table table-dark table-bordered table-hover">
<thead>
<tr>
<th width="20%">Student</th>
<th width="20%">USN</th>
<th></th>
</tr>
</thead>
<tbody>
{% for i in cl.student_set.all|dictsort:"USN"%}
<tr>
<td>{{i.name }}</td>
<td >{{i.USN}}</td>
<td>
<div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-outline-warning active">
            <input type="radio" name="{{ i.USN }}" id="option1" autocomplete="off" value="present" checked> Present
        </label>
        <label class="btn btn-outline-light">
            <input type="radio" name="{{ i.USN }}" id="option2" autocomplete="off" value="absent"> Absent
        </label>
    </div>
</td>
</tr>
{% endfor %}
</tbody>
</table>
<input class="btn btn-dark" type="submit" value="Submit">
</form>
</div>
</div>
</div>

</div>
{% endblock content %}

templates/t_examselect.html
{% extends 'base_teacher.html' %}
{% block title %}Select Exam{% endblock title %}

{% block content %}

<table class="table table-hover table-dark ">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Exam</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
{% for i in ass.marks_set.all %}
     <tr>
      <th scope="row"></th>
      <td>{{i.examname}}</td>
            {% if i.status == '0' %}
            <td><a href="{% url 't_entermarks' i.id  %}" style="color:orange;">Enter Marks</a></td>
            {% else %}
            <td><a href="{% url 't_editmarks' i.id %}">Edit Marks</a></td>
            {% endif %}
      <td></td>
    </tr>
{% endfor %}
  </tbody>
</table>
    





{% endblock content %}

templates/t_marks.html
{% extends 'base_teacher.html' %}
{% block title %}Select Class{% endblock title %}

{% block content %}

<div class="container-fluid">
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Class</th>
      <th scope="col">Subject</th>
      <th scope="col"></th>
      
    </tr>
  </thead>
  <tbody>
    
    {% for i in teacher.assign_set.all %}
    <tr>
      <td>{{i.class_id_id}}</td>
      <td>{{i.course}}</td>
      <td><a href="{% url 't_examselect' i.id %}">Enter Marks</a></td>
      
    </tr>
    {% empty %}
    <p>Student has no course</p>
    {% endfor %}

  </tbody>
</table>
</div>

{% endblock content %}